// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantMenuAPI.Data;

#nullable disable

namespace RestaurantMenuAPI.Migrations
{
    [DbContext(typeof(RestaurantMenuContext))]
    [Migration("20251125154924_FixPragmaFK")]
    partial class FixPragmaFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Platos de entrada",
                            Name = "Entradas",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Platos principales",
                            Name = "Platos Fuertes",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Deliciosos postres",
                            Name = "Postres",
                            RestaurantId = 1
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.HappyHour", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantId");

                    b.ToTable("HappyHours");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            DiscountPercentage = 20,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DiscountEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DiscountStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasHappyHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ceviche de pescado fresco",
                            HasDiscount = false,
                            HasHappyHour = false,
                            ImageUrl = "https://example.com/ceviche.jpg",
                            IsFeatured = true,
                            Name = "Ceviche",
                            Price = 25.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Plato tradicional peruano",
                            HasDiscount = false,
                            HasHappyHour = false,
                            ImageUrl = "https://example.com/lomo.jpg",
                            IsFeatured = false,
                            Name = "Lomo Saltado",
                            Price = 35.50m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Postre tradicional",
                            HasDiscount = false,
                            HasHappyHour = false,
                            ImageUrl = "https://example.com/suspiro.jpg",
                            IsFeatured = false,
                            Name = "Suspiro Limeño",
                            Price = 12.75m,
                            RestaurantId = 1
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Principal 123",
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Description = "Un restaurante de comida tradicional",
                            Email = "restaurant@example.com",
                            ImageUrl = "https://example.com/restaurant.jpg",
                            Name = "Mi Restaurante",
                            Number = "+1234567890",
                            OpeningDays = "1,2,3,4,5,6",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            PasswordHash = "hashed_password_123",
                            State = 0,
                            Views = 150
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Category", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.HappyHour", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Restaurant", "Restaurant")
                        .WithOne("HappyHour")
                        .HasForeignKey("RestaurantMenuAPI.Models.Entities.HappyHour", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Product", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.ProductCategory", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantMenuAPI.Models.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("HappyHour");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
