// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantMenuAPI.Data;

#nullable disable

namespace RestaurantMenuAPI.Migrations
{
    [DbContext(typeof(RestaurantMenuContext))]
    partial class RestaurantMenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Menu", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ProfileId = 1
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            IsFeatured = false,
                            MenuId = 1,
                            Name = "PrimerProducto",
                            SpecialCategory = 0
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Profile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "PrimerRestaurante"
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "luismiguel@gmail.com",
                            Password = "lamismadesiempre",
                            State = 0
                        });
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Menu", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Profile", "Profile")
                        .WithOne("Menu")
                        .HasForeignKey("RestaurantMenuAPI.Models.Entities.Menu", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Product", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.Menu", "Menu")
                        .WithMany("Products")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Profile", b =>
                {
                    b.HasOne("RestaurantMenuAPI.Models.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("RestaurantMenuAPI.Models.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Menu", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.Profile", b =>
                {
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantMenuAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
